version: '3'

services:
  nginx:
    build:
      context: .
        dockerfile: requirements/nginx/Dockerfile
      container_name: nginx
      ports:
        - "443:443"
      volumes:
        - ./requirements/nginx/conf/:/etc/nginx/http.d/
        - ./requirements/nginx/tools/:/etc/nginx/ssl/
        - /home/pandalaf/test-server:/var/www/
      restart: always
